meta_product_name: "Carbodata"
meta_title: "Carbodata - Healthy food and easy recipes, diabetic friendly"
meta_description: "Carbodata makes diabetes management easier by connecting you to a community that understands your needs.
                   Track your products, explore diabetes-friendly recipes shared by others,
                    and get personalized recipe ideas from SuperCarbo, our AI assistant."
meta_image: "cover.jpg"
